name: Quarto Workflow
on:
    
    push:

jobs:

    quarto-job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Quarto passo"
            - name: Checkout
              uses: actions/checkout@v5
            - name: "Verifica README.md"
              run: test -f README.md
            - name: "Verifica LICENSE"
              run: test -f LICENSE
            - name: "Verifica .gitignore"
              run: test -f .gitignore